### ISSUE TITLE
A few changes I think could improve the package

### ISSUE THREAD

**Issue by U-4-E-A** [receter/my-component-library#2]
I posted this as a comment on the dev.to article... not sure if you saw it.

**The use of `tsc` in the build command**

`"build": "tsc --p ./tsconfig-build.json && vite build"`

I believe this is redundant as you are using `vite-plugin-dts` in your `vite.config.js`, which is building the types. I have forked the repo and run it with and without the inclusion of the `tsc` command and this appears to make no difference to the output. As the sole purpose of `tsconfig-build.json` appears to be the exclusion of the `src` directory during building I believe the `tsconfig-build.json` file itself is redundant as, if what I wrote above is correct, a build-specific `tsconfig` is not required at all.

**Placement of `vite-env.d.ts` inside the `lib` directory**

This also appears to be redundant. vite does indeed need to reference it's own types but it's clutter and code duplication to have separate `vite-env-d.ts` files.

I believe the best option here to solve these issues is: -

1. Remove `tsc` from the build command, meaning `tsconfig-build.json` is now redundant and can be deleted.
2. Delete `vite-env.d.ts` from the lib directory.
3. In `tsconfig.json`, either reference the `vite-env.d.ts` file in the `src` directory in the `compilerOptions` `"types": ["./src/vite-env.d.ts"]` or simply delete all instances of the `vite-env.d.ts` file and [reference the types directory](https://vitejs.dev/guide/features#client-types) `"types": ["vite/client"]`.

I've tried the latter and have been able to both run the dev server and compile the library without issues.

Alternatively, if you want to keep the `vite-env.d.ts` file in in the `lib` directory, you can do modify the glob command in `vite.config.ts` to exclude it's output (as an empty file) in `dist`: -

```
glob.sync("lib/**/*.{ts,tsx}", {
ignore: ["lib/**/*.d.ts"],
})
```

**Comment by receter** [comment]
Hi @U-4-E-A,

Thanks for your suggestions!

`tsc` is run before the build to check for type issues. If this is removed, the project will compile despite type errors. You can check this by adding `const test: string = true;` and try to compile the project.

Excluding `src` in `tsconfig-build.json` helps avoid TypeScript errors when you import components directly from the dist folder on the demo page and those components haven't been built yet.

While you want TS to be enabled for the whole project, you want to build the project even though there are TS errors in `src` as this folder should not contain code related to the library after all. But `src` is used when running `npm run dev` so it needs to be included in the default tsconfig.

Regarding the `vite-env.d.ts` file, I do like to keep using this file as it is also what vite does by default. I think you can move this safely to `tsconfig.json`. I just don't want to do that without understanding why vite decided to use this file instead. For example vite-plugin-svgr provides a declaration helper that you can copy to this file, maybe it would confuse people if this file does not exist when it normally does in a vite project.

I am botherd by the empty js file though and your solution to ignore it for the glob looks good to me, thanks for that!

**Comment by U-4-E-A** [comment]
Great response and I stand corrected. Thank you for helping improve my understanding.
